baseURL = "https://hugo-test.onrender.com/"
languageCode = "en-us"
title = "Helvetican Digital"
theme = "airspace-hugo"

[params]
  home = "Home"
  our-expertise = "Our Expertise"
  services = "Service"

  [menu]

    [[menu.header]]
      weight = 2
      name = "Services"
      url = "services"
    [[menu.header]]
      weight = 3
      name = "Our Expertise"
      url = "our-expertise"
    [[menu.header]]
      weight = 4
      name = "Contact"
      url = "contact"

    [[menu.footer]]
      weight = 1
      name = "Our Expertise"
      url = "our-expertise"
    [[menu.footer]]
      weight = 2
      name = "Contact us"
      url = "contact"
    [[menu.footer]]
      weight = 3
      name = "Services"
      url = "services"
    [[menu.footer]]
      weight = 4
      name = "Terms of Use"
      url = "#"
    [[menu.footer]]
      weight = 5
      name = "Privacy Policy"
      url = "#"

  [params.slider]
    enable = true
    title = "A digital marketing &amp; design agency"
    subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"
    bgImage = "img/slider-bg.png"
    btnText = "Discover Our Projects"
    url = "/services"

  [params.wrapper]
    enable = true
    image = "img/wrapper-img.png"
    title = "Our Expertise"
    italic = "At Helvetican Digital, we provide a wide scope of services and digital solutions for both finance and non-finance related projects. Our dedicated team of experts is here to take on your projects and make your life easier while seeing your business prosper."
    paragraph = "Our scope of work includes but is not limited to developing digital platforms for digital finance, cryptocurrencies, wealth management domains, websites and mobile applications design and development, and digital marketing."

  [params.blog]
    enable = true
    title = "Get The Latest On What We're doing"
    subtitle = "Catch up with us, anytime and anywhere"

  [params.feature]
    enable = true
    title = "We believe in great ideas"
    bgImage = "img/feature-bg.png"
    content = "It’s the outcome of the project that gets us all excited at Helvetican Digital. We’re enthusiastic about taking on new challenges and assisting you throughout the entire project. We strongly believe that your satisfaction is our success and we will always provide you with the best solutions."
    [params.feature.button]
      caption = "View Works"
      url = "/services"

  [params.call]
    enable = true
    bgImage = "img/call-to-action-bg.jpg"
    title = "Tailored digital solutions for ambitious businesses and individuals."
    paragraph = "Contact us to learn about what we do and how we do it differently. The Helvetican Digital Team is looking forward to hearing from you."
    [params.call.button]
      url = "/contact"
      text = "Contact us"

  [params.contact]
    enable = true
    title = "Drop us a note"
    subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      full_name = "Your full name"
      email = "Your email"
      phone = "Your phone"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Our office"
      address = "Helvetican Digital, Spätzstrasse 33, 8810 Horgen, Switzerland"
      email = "team@helvetican.digital"
      phone = "+41 76 558 77 76"
    [params.contact.gmaps]
      title = "Our coordinates"
